---

- name: Run tasks as root
  become: yes
  block: 

    - name: Install prerequisites with apt
      apt:
        name: "{{ domoticz_prerequisite }}"
        state: present
        update_cache: true
      when: ansible_os_family == "Debian"

    - name: Install prerequisites with yum
      yum:
        name: "{{ domoticz_prerequisite }}"
        state: present
        update_cache: true
      when: ansible_distribution == "CentOS"

    - name: Install prerequisites with dnf
      dnf:
        name: "{{ domoticz_prerequisite }}"
        state: present
      when: ansible_distribution == "Fedora"
