---
- name: restart domoticz
  service:
    name: domoticz
    state: restarted
  become: yes

- name: make zwave
  command: make
  args:
    chdir: "{{ domoticz_dir }}/open-zwave"
    creates: "{{ domoticz_dir }}/open-zwave/MinOZW"
  become: yes
  